### ISSUE TITLE
MFA Required (2FA)

### ISSUE THREAD

**Issue by VIRUXE** [fuwwy/guilded-bridge#1]
`GuildedAPIError: [GuildedAPIError:428:POST] /login - MFA required`

Is there any other way to have this bridge to work without deactivating 2FA?

**Comment by itsfolf** [comment]
It seems like the package I use to interact with guilded has updated and supports only authentication by bot token now. I could update to that, but it seems like it's still invite-only.

**Comment by VIRUXE** [comment]
It still works. I just had to disable 2FA. It's just not ideal.
